name: Theme Deploy

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2

      # Step 2: Install Shopify CLI
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli

      # Step 3: Upload theme
      - name: Upload Theme to Shopify
        env:
          SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
        run: |
          shopify theme push \
            --theme $SHOPIFY_THEME_ID \
            --store $SHOPIFY_STORE \
            --password $SHOPIFY_CLI_THEME_TOKEN \
            -a \
            --json
